### ISSUE TITLE
UI feature requests

### ISSUE THREAD

**Issue by EMeindertsma** [alegnani/verifactory#16]
There is no scrolling in the GUI, and parts of it get hidden if the blueprint is too large (at least on Windows). (You probably already knew this.)

It would also be nice if there were a hotkey for (de)selecting entites as input/output.

**Comment by alegnani** [comment]
The, I agree, is quite bad at the moment. For larger blueprints I added an option to zoom out under the **View** menu.
The GUI definitely needs a major overhaul.

Adding the hotkeys is quite easy. "i" for input and "o" for ouput sounds reasonable, no?

**Comment by EMeindertsma** [comment]
Yeah, I think that's fine. 
Maybe even an option to deselect all inputs/outputs that are not belts would be nice for larger blueprints, but the hotkeys would already be quite nice.
